#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_h.py — 把 build/crab_data.py 转成 ESP32 用的 crab_data.h
=================================================================
ESP32 固件 #include 这个头文件后，所有像素数据放 Flash（PROGMEM/const）。
ESP32-C3 有 4MB Flash，1MB 数据占 ~26%，余裕充足。

数据结构（C++）：
  struct CrabState {
    const uint8_t* palette;                  // 512B
    uint16_t intro_count;
    const uint8_t* const* intro_frames;      // 每帧 RLE 起始指针
    const uint16_t* intro_frame_sizes;       // 每帧 RLE 长度
    uint16_t loop_count;
    const uint8_t* const* loop_frames;
    const uint16_t* loop_frame_sizes;
  };
  extern const CrabState* getStateByChar(char c);
"""
import sys
from pathlib import Path
from textwrap import indent

PROJECT = Path(__file__).resolve().parent
BUILD   = PROJECT / "build"
sys.path.insert(0, str(BUILD))
import crab_data  # noqa: E402

OUT_PATH = PROJECT / "Arduino" / "claude_status" / "crab_data.h"


def bytes_to_c_array(data: bytes, per_line: int = 16) -> str:
    """把 bytes 转成 C 数组字面量字符串：  0x12, 0x34, ..."""
    if not data:
        return "  /* empty */"
    chunks = []
    for i in range(0, len(data), per_line):
        line = ", ".join(f"0x{b:02X}" for b in data[i:i+per_line])
        chunks.append("  " + line + ",")
    # 去掉最后一个逗号
    chunks[-1] = chunks[-1].rstrip(",")
    return "\n".join(chunks)


def emit_state(state: str, data: dict, out) -> None:
    """为单个状态输出所有数据数组（palette / intro_frames / loop_frames）"""
    pal = data["palette"]
    intro_list = data.get("intro", [])
    loop_list  = data.get("loop", [])

    # palette
    out.write(f"// ============ {state} state ============\n")
    out.write(f"static const uint8_t {state}_palette[{len(pal)}] PROGMEM = {{\n")
    out.write(bytes_to_c_array(pal))
    out.write("\n};\n\n")

    # intro frames（每帧一个数组）
    for i, frame in enumerate(intro_list):
        out.write(f"static const uint8_t {state}_intro_f{i}[{len(frame)}] PROGMEM = {{\n")
        out.write(bytes_to_c_array(frame))
        out.write("\n};\n")
    if intro_list:
        out.write(f"\nstatic const uint8_t* const {state}_intro_frames[{len(intro_list)}] PROGMEM = {{\n")
        out.write(",\n".join(f"  {state}_intro_f{i}" for i in range(len(intro_list))))
        out.write("\n};\n")
        out.write(f"static const uint16_t {state}_intro_sizes[{len(intro_list)}] PROGMEM = {{\n  ")
        out.write(", ".join(str(len(f)) for f in intro_list))
        out.write("\n};\n\n")

    # loop frames
    for i, frame in enumerate(loop_list):
        out.write(f"static const uint8_t {state}_loop_f{i}[{len(frame)}] PROGMEM = {{\n")
        out.write(bytes_to_c_array(frame))
        out.write("\n};\n")
    if loop_list:
        out.write(f"\nstatic const uint8_t* const {state}_loop_frames[{len(loop_list)}] PROGMEM = {{\n")
        out.write(",\n".join(f"  {state}_loop_f{i}" for i in range(len(loop_list))))
        out.write("\n};\n")
        out.write(f"static const uint16_t {state}_loop_sizes[{len(loop_list)}] PROGMEM = {{\n  ")
        out.write(", ".join(str(len(f)) for f in loop_list))
        out.write("\n};\n\n")


def main() -> None:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    states = list(crab_data.ANIMATIONS.keys())
    # 按项目计划书的顺序排：T W N D E I
    order = ["T", "W", "N", "D", "E", "I"]
    states = [s for s in order if s in states] + [s for s in states if s not in order]

    with OUT_PATH.open("w", encoding="utf-8") as out:
        out.write("// AUTO-GENERATED by build_h.py — DO NOT EDIT\n")
        out.write("// 由 build/crab_data.py 转换而来，与 simulator.py 共用同一份字节流。\n")
        out.write("#pragma once\n\n")
        out.write("#include <Arduino.h>\n\n")
        out.write(f"constexpr int FRAME_W      = {crab_data.FRAME_W};\n")
        out.write(f"constexpr int FRAME_H      = {crab_data.FRAME_H};\n")
        out.write(f"constexpr int FPS          = {crab_data.FPS};\n")
        out.write(f"constexpr int MS_PER_FRAME = {crab_data.MS_PER_FRAME};\n\n")

        out.write("struct CrabState {\n")
        out.write("  char     id;                // 'T' 'W' 'N' 'D' 'E' 'I'\n")
        out.write("  const uint8_t* palette;     // 512B = 256 色 RGB565 (大端)\n")
        out.write("  uint16_t intro_count;       // intro 段帧数，0 表示无 intro\n")
        out.write("  const uint8_t* const* intro_frames;\n")
        out.write("  const uint16_t* intro_sizes;\n")
        out.write("  uint16_t loop_count;        // loop 段帧数\n")
        out.write("  const uint8_t* const* loop_frames;\n")
        out.write("  const uint16_t* loop_sizes;\n")
        out.write("};\n\n")

        for s in states:
            emit_state(s, crab_data.ANIMATIONS[s], out)

        # 总表
        out.write(f"constexpr int STATE_COUNT = {len(states)};\n")
        out.write("static const CrabState CRAB_STATES[STATE_COUNT] = {\n")
        for s in states:
            data = crab_data.ANIMATIONS[s]
            intro_list = data.get("intro", [])
            loop_list  = data.get("loop", [])
            intro_ptr  = f"{s}_intro_frames" if intro_list else "nullptr"
            intro_sz   = f"{s}_intro_sizes"  if intro_list else "nullptr"
            loop_ptr   = f"{s}_loop_frames"  if loop_list  else "nullptr"
            loop_sz    = f"{s}_loop_sizes"   if loop_list  else "nullptr"
            out.write(f"  {{ '{s}', {s}_palette, "
                      f"{len(intro_list)}, {intro_ptr}, {intro_sz}, "
                      f"{len(loop_list)}, {loop_ptr}, {loop_sz} }},\n")
        out.write("};\n\n")

        # 查表函数
        out.write("inline const CrabState* getStateByChar(char c) {\n")
        out.write("  for (int i = 0; i < STATE_COUNT; i++) {\n")
        out.write("    if (CRAB_STATES[i].id == c) return &CRAB_STATES[i];\n")
        out.write("  }\n")
        out.write("  return nullptr;\n")
        out.write("}\n")

    size_kb = OUT_PATH.stat().st_size / 1024
    print(f"[OK] 生成 {OUT_PATH}")
    print(f"     文件大小：{size_kb:.1f} KB（编译后实际占 Flash ~{size_kb*0.3:.0f} KB）")
    print(f"     状态：{states}")


if __name__ == "__main__":
    main()
